#!/bin/bash
#############################################################################
#
# This became a oneliner in my bashrc, it was originally 3 or 4 lines.
#
#############################################################################
dunstify -p -r 6 "Battery: $(echo $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep  -E "time\ to\ full:|percentage") | cut -d ' ' -f 2)"
