#!/bin/bash
#############################################################################
#
# I could never manage to get this in a oneliner.
# I'm not sure why.
# I guess I could do what I did but with a semicolon.
#
#############################################################################


hold=$(xinput | grep Touchscreen | cut -d '=' -f 2)

xinput --disable ${hold:0:2}
