#!/bin/bash
#--------------------------------------------
# Kinda worthless, I don't use my touchscreen.
# What I shoulda did was made it a toggle.
# Maybe later.
#---------------------------------------------
hold=$(xinput | grep Touchscreen | cut -d '=' -f 2)

xinput --enable ${hold:0:2}
