#!/bin/bash
#############################################################################
#
# Kinda worthless, I don't use my touchscreen.
# What I shoulda did was made it a toggle.
# Maybe later.
#
#############################################################################
hold=$(xinput | grep Touchscreen | cut -d '=' -f 2)

status=$(cat /tmp/ScreenStatus)
echo ${hold:0:2}
if [ "$status" = "0" ]; then
echo 1 > /tmp/ScreenStatus
xinput --disable ${hold:0:2}
else
echo 0 > /tmp/ScreenStatus
xinput --enable ${hold:0:2}
fi


